### ISSUE TITLE
BUG on functions.php line 881 [NOTES]

### ISSUE THREAD

**Issue by GrayofD4** [d4advancedmedia/Events#11]
I had an error with the events plugin - `Parse error: syntax error, unexpected '[' in /home/.../public_html/wp-content/plugins/Events-master/lib/functions.php on line 881`

The issue seems to be running functions that produce arrays as an array itself.

```$file_class = 'fileclass_'.pathinfo($meta[1])['extension']This fixes it:

            $file_path_info = pathinfo($meta[1]);
            $file_class = 'fileclass_' . $file_path_info['extension'];
```
You had perfectly valid PHP code still. It just the PHP version on certain servers.

**Comment by MerrittofD4** [comment]
Fixed with a previous revision
