### ISSUE TITLE
Filter to adjust rendering of calendar items [NOTES]

### ISSUE THREAD

**Issue by GrayofD4** [d4advancedmedia/Events#12]
If I want to add Time of day for each event on only the agenda view, etc.

**Comment by GrayofD4** [comment]
Or simply add all that in, display none at first and allow the designer to display it and style it.

**Comment by MerrittofD4** [comment]
Added with the "output_filter" shortcode attribute. Example:

`add_filter('d4events_myfilter', 'd4events_myfilter_output');

function d4events_myfilter_output($event_data) {}`
