### ISSUE TITLE
wp ajax broke on multisites [NOTES for Solution]

### ISSUE THREAD

**Issue by GrayofD4** [d4advancedmedia/Events#15]
in /index.php `register_d4events_elements()` add 
`wp_localize_script( 'd4events', 'ajax_object', array( 'ajaxurl' => admin_url( 'admin-ajax.php' ) ) ); // setting ajaxurl` right under `wp_enqueue_script('d4events');`

in /js/d4events.js replace `/wp-admin/admin-ajax.php,` with `ajax_object.ajaxurl,`

**Comment by MerrittofD4** [comment]
Patched in previous update
